[input]
html_selector = "main"
base_directory = "output"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "posts/2023/11/welcome-to-teapotnz/index.html"
url = "/posts/2023/11/welcome-to-teapotnz/"
title = "Welcome to Teapot.nz"
